#!/bin/sh
# Script to modify the `updated` field in the YAML front matter
# 
# Since git does not keep track of hooks in .git/hooks, there is this script in the main project directory (not in .git)
# It should be symlinked to .git/hooks/pre-commits

git diff --cached --name-status | grep "^M" | while read a b; do
  cat $b | sed "/---.*/,/---.*/s/^last-modified:.*$/last-modified: $(date -u "+%Y-%m-%d %T %Z")/" > tmp
  mv tmp $b
  git add $b
done
